### ISSUE TITLE
MYSQL - build or pull?

### ISSUE THREAD

**Issue by gilwi** [tzgued/Docker-PHP-Symfony-Angular#1]
Hi,
I ran your template to bootstrap a quick demo of the technologies used in the project, many thanks for providing it!
But by default, I had trouble with the MYSQL container which didn't let me log in.

I noticed you have a `.docker/mysql` directory that is not used, the compose file pulling directly mysql:5.7, are you planning to move to a custom mysql container?

Then, my real issue was your default `.env` file that didn't get parsed properly (spaces and quotes).
May I submit a PR fixing this typo?

Best regards

**Comment by gilwi** [comment]
Submitted a PR addressing this issue, see `fix env file typos`

**Comment by tzgued** [comment]
thanks man. sorry, sorry I've been very busy lately to follow up with this repo

**Comment by gilwi** [comment]
see [here](https://github.com/tzgued/Docker-PHP-Symfony-Angular/pull/2)
